import { Router } from "express";
import authRoutes from "./auth.js";
import contactRoutes from "./contact.js";
import telemetryRoutes from "./telemetry.js";
import usersRoutes from "./users.js";
import propertiesRoutes from "./properties.js";
import listingsRoutes from "./listings.js";
import agentsRoutes from "./agents.js";
import inquiriesRoutes from "./inquiries.js";
import favoritesRoutes from "./favorites.js";
import savedSearchesRoutes from "./savedSearches.js";
import adminRoutes from "./admin.js";
import uploadsRoutes from "./uploads.js";
import mortgageRoutes from "./mortgage.js";
import marketRoutes from "./market.js";
import neighborhoodsRoutes from "./neighborhoods.js";
import paymentsRoutes from "./payments.js";
import documentsRoutes from "./documents.js";
import locationsRoutes from "./locations.js";
import developerProjectsRoutes from "./developerProjects.js";
import projectPhasesRoutes from "./projectPhases.js";
import projectUnitsRoutes from "./projectUnits.js";
import tenantsRoutes from "./tenants.js";
import maintenanceRequestsRoutes from "./maintenanceRequests.js";
import supportTicketsRoutes from "./supportTickets.js";
import systemSettingsRoutes from "./systemSettings.js";
import mortgageApplicationsRoutes from "./mortgageApplications.js";
import kycRoutes from "./kyc.js";
import geoRoutes from "./geo.js";
import availabilityRoutes from "./availability.js";
import analyticsRoutes from "./analytics.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/contact", contactRoutes);
router.use("/telemetry", telemetryRoutes);
router.use("/users", usersRoutes);
router.use("/properties", propertiesRoutes);
router.use("/listings", listingsRoutes);
router.use("/agents", agentsRoutes);
router.use("/inquiries", inquiriesRoutes);
router.use("/favorites", favoritesRoutes);
router.use("/saved-searches", savedSearchesRoutes);
router.use("/admin", adminRoutes);
router.use("/uploads", uploadsRoutes);
router.use("/mortgage", mortgageRoutes);
router.use("/market", marketRoutes);
router.use("/neighborhoods", neighborhoodsRoutes);
router.use("/payments", paymentsRoutes);
router.use("/documents", documentsRoutes);
router.use("/locations", locationsRoutes);
router.use("/developer-projects", developerProjectsRoutes);
router.use("/project-phases", projectPhasesRoutes);
router.use("/project-units", projectUnitsRoutes);
router.use("/tenants", tenantsRoutes);
router.use("/maintenance-requests", maintenanceRequestsRoutes);
router.use("/support-tickets", supportTicketsRoutes);
router.use("/system-settings", systemSettingsRoutes);
router.use("/mortgage-applications", mortgageApplicationsRoutes);
router.use("/kyc", kycRoutes);
router.use("/geo", geoRoutes);
router.use("/availability", availabilityRoutes);
router.use("/admin/analytics", analyticsRoutes);

export default router;
