// Seed dataset for the frontend-only demo build (VITE_DEMO_MODE=true).
// Field names intentionally mirror the real Prisma models (Property, Listing,
// Inquiry, User) plus the alternate names pages fall back to, since pages
// were written to accept either shape (see src/lib/normalizers.ts).
//
// Photos are bundled locally (no external image service at runtime) — a mix
// of the app's existing marketing photos and a small curated set of CC0
// stock photos in ./assets, reused across listings since there are more
// demo properties than distinct source photos.
import exteriorVilla from "../../assets/img/property-1.jpg";
import exteriorAptDay from "../../assets/img/property-2.jpg";
import exteriorAptDusk from "../../assets/img/property-3.jpg";
import interiorLiving from "../../assets/img/demo/living02.jpg";
import interiorCozy from "../../assets/img/demo/kitchen01.jpg";

export const DEMO_CREDENTIALS = {
  buyer: { email: "buyer@demo.estatein.com", password: "Demo1234!", name: "Aisha Wanjiru" },
  agent: { email: "agent@demo.estatein.com", password: "Demo1234!", name: "Brian Otieno" },
  admin: { email: "admin@demo.estatein.com", password: "Demo1234!", name: "Grace Mwangi" },
} as const;

export const DEMO_USERS = [
  {
    id: "demo-user-buyer",
    email: DEMO_CREDENTIALS.buyer.email,
    name: DEMO_CREDENTIALS.buyer.name,
    phone: "+254712000001",
    role: "buyer" as const,
    verified: true,
    twoFactorEnabled: false,
    createdAt: "2025-01-15T09:00:00.000Z",
  },
  {
    id: "demo-user-agent",
    email: DEMO_CREDENTIALS.agent.email,
    name: DEMO_CREDENTIALS.agent.name,
    phone: "+254712000002",
    role: "agent" as const,
    verified: true,
    twoFactorEnabled: false,
    company: "Skyline Realty Nairobi",
    license: "EAB-2024-8831",
    licenseState: "Nairobi",
    agent: { id: "demo-agent-1" },
    createdAt: "2024-11-02T09:00:00.000Z",
  },
  {
    id: "demo-user-admin",
    email: DEMO_CREDENTIALS.admin.email,
    name: DEMO_CREDENTIALS.admin.name,
    phone: "+254712000003",
    role: "admin" as const,
    verified: true,
    twoFactorEnabled: false,
    createdAt: "2024-06-01T09:00:00.000Z",
  },
];

export const DEMO_AGENTS = [
  {
    id: "demo-agent-1",
    userId: "demo-user-agent",
    name: DEMO_CREDENTIALS.agent.name,
    email: DEMO_CREDENTIALS.agent.email,
    brokerage: "Skyline Realty Nairobi",
    licenseNumber: "EAB-2024-8831",
    serviceAreas: ["Nairobi", "Kiambu"],
    specialties: ["Residential", "Off-plan"],
    totalSales: 42,
    averageSalePrice: 12_500_000,
    rating: 4.8,
    reviewCount: 19,
    verified: true,
    bio: "Helping Nairobi families find home for over 8 years.",
  },
];

export const DEMO_PROPERTIES = [
  {
    id: "demo-prop-1",
    slug: "demo-prop-1",
    title: "Modern 4-Bedroom Villa in Runda",
    name: "Modern 4-Bedroom Villa in Runda",
    address: "12 Runda Grove Close",
    city: "Nairobi",
    county: "Nairobi",
    estate: "Runda",
    propertyType: "villa",
    beds: 4,
    baths: 4,
    sqFt: 3800,
    price: 45_000_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description:
      "A beautifully finished villa set on a quarter-acre in Runda, with a manicured garden, staff quarters, and 24-hour estate security.",
    features: ["Backup generator", "Solar water heating", "Borehole", "CCTV"],
    amenities: ["parking", "pool", "gym", "security"],
    photos: [exteriorVilla, interiorLiving],
    views: 482,
    favorites: 37,
    inquiries: 6,
    furnished: false,
    parking: true,
    pool: true,
    gym: false,
    security: true,
    lat: -1.2206,
    lng: 36.8172,
    createdAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "demo-prop-2",
    slug: "demo-prop-2",
    title: "2-Bedroom Apartment in Kilimani",
    name: "2-Bedroom Apartment in Kilimani",
    address: "Wood Avenue",
    city: "Nairobi",
    county: "Nairobi",
    estate: "Kilimani",
    propertyType: "apartment",
    beds: 2,
    baths: 2,
    sqFt: 1150,
    price: 12_800_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description:
      "Contemporary apartment in a gated Kilimani development, walking distance to Yaya Centre, with a rooftop lounge and gym.",
    features: ["Rooftop lounge", "Fibre internet", "Elevator"],
    amenities: ["parking", "gym", "internet", "security"],
    photos: [exteriorAptDay, interiorCozy],
    views: 301,
    favorites: 22,
    inquiries: 4,
    furnished: true,
    parking: true,
    gym: true,
    security: true,
    lat: -1.2921,
    lng: 36.7833,
    createdAt: "2026-05-10T10:00:00.000Z",
  },
  {
    id: "demo-prop-3",
    slug: "demo-prop-3",
    title: "3-Bedroom Townhouse in Nyali",
    name: "3-Bedroom Townhouse in Nyali",
    address: "Links Road",
    city: "Mombasa",
    county: "Mombasa",
    estate: "Nyali",
    propertyType: "townhouse",
    beds: 3,
    baths: 3,
    sqFt: 2100,
    price: 22_000_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Coastal-style townhouse minutes from Nyali beach, with an open-plan kitchen and a private courtyard.",
    features: ["Private courtyard", "Servant quarter", "Ample parking"],
    amenities: ["parking", "security"],
    photos: [exteriorVilla, interiorLiving],
    views: 198,
    favorites: 14,
    inquiries: 2,
    parking: true,
    security: true,
    lat: -4.0263,
    lng: 39.7086,
    createdAt: "2026-05-28T10:00:00.000Z",
  },
  {
    id: "demo-prop-4",
    slug: "demo-prop-4",
    title: "1-Bedroom Rental in Westlands",
    name: "1-Bedroom Rental in Westlands",
    address: "Waiyaki Way",
    city: "Nairobi",
    county: "Nairobi",
    estate: "Westlands",
    propertyType: "apartment",
    beds: 1,
    baths: 1,
    sqFt: 650,
    price: 65_000,
    currency: "KSH",
    listingStatus: "for_rent",
    description: "Cozy, fully-furnished 1-bedroom close to Westlands' nightlife and offices — ideal for young professionals.",
    features: ["Fully furnished", "Backup water"],
    amenities: ["parking", "internet"],
    photos: [exteriorAptDusk, interiorCozy],
    views: 260,
    favorites: 11,
    inquiries: 3,
    furnished: true,
    parking: true,
    lat: -1.2673,
    lng: 36.8065,
    createdAt: "2026-06-15T10:00:00.000Z",
  },
  {
    id: "demo-prop-5",
    slug: "demo-prop-5",
    title: "5-Bedroom Family Home in Karen",
    name: "5-Bedroom Family Home in Karen",
    address: "Karen Road",
    city: "Nairobi",
    county: "Nairobi",
    estate: "Karen",
    propertyType: "house",
    beds: 5,
    baths: 5,
    sqFt: 5200,
    price: 68_000_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Half-acre family home in Karen with mature gardens, a swimming pool, and a separate guest wing.",
    features: ["Mature garden", "Guest wing", "Solar power"],
    amenities: ["parking", "pool", "security"],
    photos: [exteriorVilla, interiorLiving],
    views: 355,
    favorites: 29,
    inquiries: 5,
    parking: true,
    pool: true,
    security: true,
    lat: -1.3197,
    lng: 36.7076,
    createdAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "demo-prop-6",
    slug: "demo-prop-6",
    title: "3-Bedroom Apartment for Rent in Lavington",
    name: "3-Bedroom Apartment for Rent in Lavington",
    address: "James Gichuru Road",
    city: "Nairobi",
    county: "Nairobi",
    estate: "Lavington",
    propertyType: "apartment",
    beds: 3,
    baths: 3,
    sqFt: 1600,
    price: 140_000,
    currency: "KSH",
    listingStatus: "for_rent",
    description: "Spacious family apartment in leafy Lavington, close to international schools and shopping malls.",
    features: ["Balcony", "Backup generator", "Children's play area"],
    amenities: ["parking", "gym", "security"],
    photos: [exteriorAptDay, interiorCozy],
    views: 174,
    favorites: 9,
    inquiries: 2,
    furnished: false,
    parking: true,
    gym: true,
    security: true,
    lat: -1.2807,
    lng: 36.7692,
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    id: "demo-prop-7",
    slug: "demo-prop-7",
    title: "3-Bedroom Townhouse in Kileleshwa",
    name: "3-Bedroom Townhouse in Kileleshwa",
    address: "Othaya Road",
    city: "Nairobi",
    county: "Nairobi",
    estate: "Kileleshwa",
    propertyType: "townhouse",
    beds: 3,
    baths: 3,
    sqFt: 1950,
    price: 26_500_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Gated townhouse development in Kileleshwa with a shared clubhouse and landscaped courtyards.",
    features: ["Shared clubhouse", "Fibre internet", "Ample visitor parking"],
    amenities: ["parking", "security"],
    photos: [exteriorAptDusk, interiorLiving],
    views: 142,
    favorites: 8,
    inquiries: 1,
    parking: true,
    security: true,
    lat: -1.2833,
    lng: 36.7833,
    createdAt: "2026-06-30T10:00:00.000Z",
  },
  {
    id: "demo-prop-8",
    slug: "demo-prop-8",
    title: "4-Bedroom Beachside House in Bamburi",
    name: "4-Bedroom Beachside House in Bamburi",
    address: "Bamburi Beach Road",
    city: "Mombasa",
    county: "Mombasa",
    estate: "Bamburi",
    propertyType: "house",
    beds: 4,
    baths: 4,
    sqFt: 2900,
    price: 32_000_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Breezy coastal home minutes from Bamburi Beach, with a wraparound veranda and mature palm garden.",
    features: ["Wraparound veranda", "Outdoor shower", "Borehole"],
    amenities: ["parking", "security"],
    photos: [exteriorVilla, interiorCozy],
    views: 121,
    favorites: 10,
    inquiries: 2,
    parking: true,
    security: true,
    lat: -4.0004,
    lng: 39.7178,
    createdAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "demo-prop-9",
    slug: "demo-prop-9",
    title: "2-Bedroom Lakeside Apartment in Kisumu",
    name: "2-Bedroom Lakeside Apartment in Kisumu",
    address: "Milimani Estate",
    city: "Kisumu",
    county: "Kisumu",
    estate: "Milimani",
    propertyType: "apartment",
    beds: 2,
    baths: 2,
    sqFt: 1050,
    price: 55_000,
    currency: "KSH",
    listingStatus: "for_rent",
    description: "Bright apartment overlooking Lake Victoria, walking distance to Kisumu's central business district.",
    features: ["Lake views", "Backup water", "Balcony"],
    amenities: ["parking", "internet"],
    photos: [exteriorAptDay],
    views: 96,
    favorites: 6,
    inquiries: 1,
    furnished: true,
    parking: true,
    lat: -0.0917,
    lng: 34.7679,
    createdAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "demo-prop-10",
    slug: "demo-prop-10",
    title: "4-Bedroom Family House in Nakuru",
    name: "4-Bedroom Family House in Nakuru",
    address: "Milimani Road",
    city: "Nakuru",
    county: "Nakuru",
    estate: "Milimani",
    propertyType: "house",
    beds: 4,
    baths: 3,
    sqFt: 2600,
    price: 18_500_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Established family home in Nakuru's Milimani area, close to schools and Lake Nakuru National Park.",
    features: ["Large garden", "Solar water heating", "Servant quarter"],
    amenities: ["parking", "security"],
    photos: [exteriorVilla],
    views: 88,
    favorites: 5,
    inquiries: 1,
    parking: true,
    security: true,
    lat: -0.2833,
    lng: 36.0667,
    createdAt: "2026-07-08T10:00:00.000Z",
  },
  {
    id: "demo-prop-11",
    slug: "demo-prop-11",
    title: "3-Bedroom Townhouse in Eldoret",
    name: "3-Bedroom Townhouse in Eldoret",
    address: "Elgon View",
    city: "Eldoret",
    county: "Uasin Gishu",
    estate: "Elgon View",
    propertyType: "townhouse",
    beds: 3,
    baths: 3,
    sqFt: 1800,
    price: 15_800_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Modern townhouse in Eldoret's Elgon View, in a quiet gated community close to top schools.",
    features: ["Gated community", "Backup generator", "Ample parking"],
    amenities: ["parking", "security"],
    photos: [exteriorAptDusk],
    views: 64,
    favorites: 4,
    inquiries: 0,
    parking: true,
    security: true,
    lat: 0.5143,
    lng: 35.2698,
    createdAt: "2026-07-11T10:00:00.000Z",
  },
  {
    id: "demo-prop-12",
    slug: "demo-prop-12",
    title: "Half-Acre Residential Plot in Ruiru",
    name: "Half-Acre Residential Plot in Ruiru",
    address: "Kiambu Road Extension",
    city: "Nairobi",
    county: "Kiambu",
    estate: "Ruiru",
    propertyType: "land",
    beds: 0,
    baths: 0,
    sqFt: 21_780,
    price: 8_500_000,
    currency: "KSH",
    listingStatus: "for_sale",
    description: "Ready-to-build half-acre plot with a title deed in hand, in a fast-growing Ruiru residential zone.",
    features: ["Title deed ready", "Electricity at the road", "Murram access road"],
    amenities: [],
    photos: [exteriorVilla],
    views: 73,
    favorites: 7,
    inquiries: 1,
    parking: false,
    security: false,
    lat: -1.1467,
    lng: 36.9614,
    createdAt: "2026-07-14T10:00:00.000Z",
  },
  {
    id: "demo-prop-13",
    slug: "demo-prop-13",
    title: "Studio Apartment for Rent in Kisumu",
    name: "Studio Apartment for Rent in Kisumu",
    address: "Nyerere Road",
    city: "Kisumu",
    county: "Kisumu",
    estate: "Milimani",
    propertyType: "apartment",
    beds: 1,
    baths: 1,
    sqFt: 450,
    price: 28_000,
    currency: "KSH",
    listingStatus: "for_rent",
    description: "Compact, affordable studio near Kisumu town center — ideal for a single professional or student.",
    features: ["Fully tiled", "Backup water"],
    amenities: ["internet"],
    photos: [interiorCozy],
    views: 52,
    favorites: 3,
    inquiries: 0,
    furnished: false,
    lat: -0.1022,
    lng: 34.7617,
    createdAt: "2026-07-16T10:00:00.000Z",
  },
];

// The two most recently created listings are left "pending" so the admin
// moderation queue (getPendingListings/approveListing/rejectListing) has
// something to act on in the demo instead of showing an empty queue.
const PENDING_PROPERTY_IDS = new Set(["demo-prop-12", "demo-prop-13"]);

export const DEMO_LISTINGS = DEMO_PROPERTIES.map((p, i) => ({
  id: `demo-listing-${i + 1}`,
  userId: "demo-user-agent",
  propertyId: p.id,
  title: p.title,
  description: p.description,
  listingType: p.listingStatus,
  price: p.price,
  status: PENDING_PROPERTY_IDS.has(p.id) ? "pending" : "approved",
  views: p.views,
  favorites: p.favorites,
  inquiries: p.inquiries,
  createdAt: p.createdAt,
  property: p,
  user: { name: DEMO_CREDENTIALS.agent.name },
}));

export const DEMO_INQUIRIES = [
  {
    id: "demo-inquiry-1",
    propertyId: "demo-prop-1",
    listingId: "demo-listing-1",
    buyerId: "demo-user-buyer",
    sellerId: "demo-user-agent",
    buyerName: DEMO_CREDENTIALS.buyer.name,
    buyerEmail: DEMO_CREDENTIALS.buyer.email,
    subject: "Interested in the Runda villa",
    message: "Hi, I'd love to schedule a viewing for this weekend if possible. Is Saturday morning available?",
    status: "New",
    contactMethod: "Email",
    viewingRequested: true,
    viewingDate: null as string | null,
    viewingTime: "10:00",
    viewingStatus: "requested",
    read: false,
    createdAt: "2026-07-10T08:30:00.000Z",
    property: DEMO_PROPERTIES[0],
  },
  {
    id: "demo-inquiry-2",
    propertyId: "demo-prop-2",
    listingId: "demo-listing-2",
    buyerId: "demo-user-buyer",
    sellerId: "demo-user-agent",
    buyerName: DEMO_CREDENTIALS.buyer.name,
    buyerEmail: DEMO_CREDENTIALS.buyer.email,
    subject: "Question about the Kilimani apartment",
    message: "Is the price negotiable, and is parking included for a second car?",
    status: "New",
    contactMethod: "Phone",
    viewingRequested: false,
    viewingDate: null as string | null,
    viewingTime: undefined as string | undefined,
    viewingStatus: undefined as string | undefined,
    read: true,
    createdAt: "2026-07-14T14:00:00.000Z",
    property: DEMO_PROPERTIES[1],
  },
  {
    id: "demo-inquiry-3",
    propertyId: "demo-prop-5",
    listingId: "demo-listing-5",
    buyerId: "demo-user-buyer",
    sellerId: "demo-user-agent",
    buyerName: DEMO_CREDENTIALS.buyer.name,
    buyerEmail: DEMO_CREDENTIALS.buyer.email,
    subject: "Viewing confirmed — Karen family home",
    message: "Looking forward to seeing the Karen property in person. Thanks for confirming!",
    status: "Contacted",
    contactMethod: "Email",
    viewingRequested: true,
    viewingDate: "2026-07-22T00:00:00.000Z",
    viewingTime: "15:30",
    viewingStatus: "confirmed",
    read: true,
    createdAt: "2026-07-05T09:15:00.000Z",
    property: DEMO_PROPERTIES[4],
  },
];

export const DEMO_FAVORITES = ["demo-prop-2", "demo-prop-5", "demo-prop-8"];

export const DEMO_ADMIN_STATS = {
  totalUsers: 1284,
  totalListings: 356,
  activeListings: 341,
  pendingApprovals: 2,
  totalInquiries: 312,
  totalAgents: 48,
  totalRevenue: 18_450_000,
  monthlyGrowth: 12.4,
};

export const DEMO_ANALYTICS_OVERVIEW = {
  totalViews: 24680,
  totalInquiries: 312,
  totalFavorites: 890,
  conversionRate: 4.1,
  viewsTrend: [120, 150, 180, 210, 260, 300, 340],
  inquiriesTrend: [8, 10, 9, 14, 16, 18, 21],
};

export const DEMO_MARKET_TRENDS = {
  medianPrice: 14_200_000,
  priceChangeYoY: 6.8,
  averageDaysOnMarket: 34,
  inventory: 128,
};
